-libraryjars C:\WTK22\lib\wma11.jar;C:\WTK22\lib\mmapi.jar;C:\WTK22\lib\midpapi10.jar;C:\WTK22\lib\cldcapi10.jar
-injars C:\WTK22\apps\ProyFinal\bin\ProyFinal.jar
-outjar C:\DOCUME~1\familia\CONFIG~1\Temp\ProyFinal.jar
-keep public class * extends javax.microedition.midlet.MIDlet 
